//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mercury.Shop.Dal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class MercuryDbConnection : DbContext
    {
        public MercuryDbConnection()
            : base("name=MercuryDbConnection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Product> Product { get; set; }
    
        public virtual int GenerateMockProducts(Nullable<int> rowsCount)
        {
            var rowsCountParameter = rowsCount.HasValue ?
                new ObjectParameter("rowsCount", rowsCount) :
                new ObjectParameter("rowsCount", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GenerateMockProducts", rowsCountParameter);
        }
    }
}
