CREATE LOGIN [MercuryLogin]
    WITH PASSWORD = N'1', DEFAULT_DATABASE = [MercuryDb], DEFAULT_LANGUAGE = [русский], CHECK_POLICY = OFF;

/*
CREATE LOGIN [MercuryLogin]
    WITH PASSWORD = N'Pkkc4p7|E{ttgG!bgcg>xdUqmsFT7_&#$!~<v`{|_`|IyLD3', SID = 0x56AB30ADBF9A1D4CB9ABF78149DE95A6, DEFAULT_DATABASE = [MercuryDb], DEFAULT_LANGUAGE = [русский], CHECK_POLICY = OFF;
*/
